### ISSUE TITLE
ActivateConnection goes into bad state if NetworkManager is down

### ISSUE THREAD

**Issue by naveedhd** [seveas/python-networkmanager#25]
If we use `NetworkManager.NetworkManager.ActivateConnection(connections, device, "/")` when NetworkManager is down it would give error which is obvious. 

However when the NetworkManager is started, it keeps on throwing the same error.

```
bus = dbus.SystemBus()
NM_BUSNAME = 'org.freedesktop.NetworkManager'

while True:
    if bus.name_has_owner(NM_BUSNAME):
        try:
            print "Connecting to ", conn
            NetworkManager.NetworkManager.ActivateConnection(connections[conn], device, "/")
        except dbus.exceptions.DBusException as e:
            print e
    else:
        print "NetworkManager bus not available"

    print "Sleeping"
    time.sleep(10.0)
```

and my output goes like this:
```
Connecting to  <network>
Sleeping
NetworkManager bus not present
Sleeping
Connecting to  <network>
org.freedesktop.DBus.Error.ServiceUnknown: The name :1.70 was not provided by any .service files
Sleeping
Connecting to  <network>
org.freedesktop.DBus.Error.ServiceUnknown: The name :1.70 was not provided by any .service files
```

**Comment by naveedhd** [comment]
The traceback of error:

```
Traceback (most recent call last):  
  File "/usr/local/lib/python2.7/dist-packages/NetworkManager.py", line 117, in proxy_call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.188 was not provided by any .service files
```

**Comment by naveedhd** [comment]
The only way to recover from this is to reload the module and reassign device and connections.

**Comment by seveas** [comment]
In 1.2, released just the other day, I implemented a solution for this. You will need to call the auto_reconnect() method of the NetworkManager object at the start of your program. Do note that this requires your application to be run in a mainloop instead of using sleep, as good dbus citizens are required to.

You can find an example of how to use this on https://github.com/seveas/dotfiles/blob/master/bin/autovpn

**Comment by naveedhd** [comment]
@seveas in my code I have chunks of blocking code, for instance scanning for networks, sleeping for few seconds after switching connections. which are kind of 'sleep' routines. Are these going to affect the dbus communications?

**Comment by seveas** [comment]
Yes, you'll want to avoid sleeps and use events and timers instead. Sleeps and mainloops are not friends.
