### ISSUE TITLE
Crash at import

### ISSUE THREAD

**Issue by vidstige** [seveas/python-networkmanager#26]
First off, thanks for a great library. 

I have one really big nit. Normally in python modules when you import then they define functions and classes, but does not execute code. This happens when you _call_ functions or create objects. However, with NetworkManager, it starts making dbus calls and shit as soon as I _import_ the module. This cannot be right, and causes huge issues. On our buildserver for example there is no network-manager running and your nice library NetworkManager cannot even be imported, even though the tests never calls a single function from the module, but merely _imports_ it.

You can still have singletons, but that are created lazily using e.g. a static function in the NetworkManager class like so

```
NetworkManager.NetworkManager.get_instance()
```

This would resolve many problems for me (and probably others) and make this awesome NetworkManager module work more like a normal python module.

**Comment by seveas** [comment]
On vr, 2016-08-26 at 01:58 -0700, Samuel Carlsson wrote:
> Normally in python modules when you import
> then they define functions and classes, but does not execute code. 

That's really very far from the truth. You're forgetting at least
imports, setting module-level variables, python 2/3 compatibility code 

Take for instance the site.py module, which is even loaded by default.
Executes lots of things upon import. Or six, which pretty much
dynamically generates itself upon umport.

> This happens when you call functions or create objects. However, with
> NetworkManager, it starts making dbus calls and shit as soon as I
> import the module. This cannot be right, and causes huge issues. On
> our buildserver for example there is no network-manager running and
> your nice library NetworkManager cannot even be imported, even though
> the tests never calls a single function from the module, but merely
> imports it.

That's a bug in your tests. If you don't use NetworkManager, don't
import python-networkmanager.

D.

**Comment by vidstige** [comment]
Thanks for your quick reply. :+1:

Let's make more relevant comparisions on how modules are implemented in python. I chose a few I've been using, that also communicate with other parts, just like python-networkmanager.

* pyserial - Possible to import module without any serial device connected.
* requests - Possible to import library without internet connection.

What these have in common is that you can import the module regardless of whether you will later be able to call the functions. In this company python-networkmanager unfortunately stick out as less pleasant to use.

Let's assume my tests _are_ broken. How would a good test look according to you? Realize there is no way to mock NetworkManager as it cannot even be imported.

I understand you want singleton semantics, so that multiple objects cannot be created. But please consider this, perhaps there is some good solution you would be happy with?

**Comment by seveas** [comment]
Your comparison is quite flawed. pyserial/requests communicate with non-local things, be it internet hosts or a serial device. The NetworkManager module only communicates with a local NetworkManager instance. If you're not running NetworkManager, you should not use this module.

**Comment by vidstige** [comment]
This get's even more problematic when you consider signals. Now you have to call some mainloop function stuff _before_ importing NetworkManager? I'm sorry but this does not make any sense. Normally you _first_ import all your stuff and then execute code.

**Comment by seveas** [comment]
I think it's time you familiarize yourself more with dbus. What you wrote there is definitely incorrect. You'll need to set up the mainloop before trying to do anything asynchronous (like listening to signals, which auto_reconnect does), not before you import things. The whole reason auto_reconnect is a function you need to call separately is to avoid having to set up a mainloop before importing NetworkManager.

**Comment by vidstige** [comment]
Actually if you look at [examples/listener.py:5](https://github.com/seveas/python-networkmanager/blob/master/examples/listener.py#L5) you can see the statement `dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)`being called right after `dbus` is important. This is not optional, but needs to be called after dbus import but before NetworkManager import. All those weird import dependencies with need to call methods in between, makes it a hassle to use. Not to mention that all this needs a `try` wrap around it. Anyway, I though of a way of doing this in an opt-in way, e.g. current users of this lib won't be affected by the change, but if you want a slicker way of importing NetworkManager that will be possoble. Please at least consider it. Sometimes it easier to explain things in code rather than in words. :-)

**Comment by seveas** [comment]
Nope. That call does not necessarily need to be there, it just needs to be done before any async dbus functionality is used. I like to put it right after the import, but that is not necessary.

**Comment by vidstige** [comment]
Nope. Please try things before speculating wildly. Just tried that on fairly fresh Ubuntu 16.04. Anyway. a pr suggestion coming your way shortly. Bon appetite :-)

**Comment by seveas** [comment]
Hmm, that's supposed to work, so you finally found a bug. I started fixing that, but got a bit excited, this is turning into a rewrite of the code generator, so it'll take a little while.

**Comment by vidstige** [comment]
Hehe, no stress at all. Let me know if I can help out somehow, e.g. testing or so.

**Comment by seveas** [comment]
Testing can now be done, I pushed some commits to master that completely redo the class generation and signal handling.

**Comment by vidstige** [comment]
Cool, I'll check out the latest release right away!

**Comment by vidstige** [comment]
Alright, tested upgrading and works perfectly. Love the new `OnSignalName` functions. I saw you left the old signal handler connect function, but it did not work out of the box. I'm very happy with updating my code though. Next stop: Test if the unit tests will fly. :-)

**Comment by seveas** [comment]
Hmm, what did connect_to_signal do wrong for you?

Careful with the unit tests, see the README.

**Comment by vidstige** [comment]
I used it like so. `wifi` here is a `Wireless` NetworkManager instance.

```python
def handler(*args, **kwargs):
  print(args[0] if len(args) > 0 else 'Nope')

d_args = dict([(x + '_keyword', 'd_' + x) for x in ('sender', 'destination', 'interface', 'member', 'path')])
wifi.connect_to_signal('PropertiesChanged', handler, **d_args)
```

I don't remember the exact error. I think args list was always empty or something like that. Anyway, don't bother too much with this. The new syntax for signals is much better. :+1:
