### ISSUE TITLE
Question: Getting error messages?

### ISSUE THREAD

**Issue by vidstige** [seveas/python-networkmanager#27]
How do I retrieve error messages from NetworkManager?

I'm just doing `AddAndActivateConnection` call to the `NetworkManager`, however, regardless of password I am entering I'm not getting any exceptions or error messages back. When using the nmcli command line client to do the same thing I get a nice error message like so: 

    Error: Connection activation failed: (7) Secrets were required, but not provided.

How do I check whether activating a connection succeeded, and if it did not, the error message?

I also posted a question on [stackoverflow](http://stackoverflow.com/questions/39206620/getting-networkmanager-errors) if you feel that's more appropriate! :-)

**Comment by seveas** [comment]
AddAndActivateConnection returns immediately after adding the connection. Whether the activation succeeds or not can be determined by listening to signals from NetworkManager, which is what nmcli does.

**Comment by vidstige** [comment]
Great, alright. Thanks a lot! I'm new to dbus and all. :-)
