### ISSUE TITLE
Crash on non-utf8 SSIDs

### ISSUE THREAD

**Issue by vidstige** [seveas/python-networkmanager#30]
I encountered some access points with SSID byte sequences not decodable as utf-8. Here are two examples

* b'\xe9\x87\x91\xe8\xbf\xaa\xe9\xab\x9899999'
* b'MERCURY_\xe8\x80\x81\xe7\x8e\x8b'

Here NetworkManager bails out like so

```
  File "/usr/local/lib/python3.5/dist-packages/NetworkManager.py", line 81, in get_func
    return self.postprocess(name, self.unwrap(data))
  File "/usr/local/lib/python3.5/dist-packages/NetworkManager.py", line 299, in postprocess
    return fixups.ssid_to_python(val)
  File "/usr/local/lib/python3.5/dist-packages/NetworkManager.py", line 425, in ssid_to_python
    return bytes("",'ascii').join(ssid).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 2: invalid start byte
```

It's fairly easy to catch, but harder to get raw bytes to do something more meaningful with. Perhaps there could be another function on the `AccessPoint` class for example, get_raw_ssid` that returns a `bytes` object.

Whats your thoughts on this @seveas ?

**Comment by seveas** [comment]
My thought is that people who don't use encodings other than ascii or utf-8 should join wake up and join the 21st century...

A more useful thought would be to return the raw bytes if decoding fails, or decoding with error=replace.

**Comment by vidstige** [comment]
haha, I know, what's wrong with people. :-)

Thanks for your input. I think it is fine if this property raises an exception, but I would prefer to have a separate `RawSsid` or something, otherwise you have to check the return type as it might sometimes return bytes and sometimes utf-8 str. But both of your suggestions sounds fine! :+1: If I find the time, I'll make a pull request. For now I'm just catching the exception and using a string "[non-decodable]". This, I feel also has an educational effect.

**Comment by seveas** [comment]
ea936af implements the simplest workaround: warn and decode as much as possible.

**Comment by vidstige** [comment]
Awesome, thanks a lot :+1:
