### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by bochecha** [seveas/python-networkmanager#34]
Release 2.0.0 broke the compatibility with the NetworkManager in Debian Jessie.

It's been fixed with cad4dc79efd8d29e9fe1f1cd03f76e61534af808. Thank you for the fix!

Could we have a 2.0.1 release uploaded to Pypi? 😄

**Comment by seveas** [comment]
Yeah, that's probably a good idea. Didn't get any reports of other breakage.
