### ISSUE TITLE
Add NM D-BUS API constants

### ISSUE THREAD

**Issue by da2x** [seveas/python-networkmanager#39]
Package should include the D-BUS API constants for NetworkManager.

https://developer.gnome.org/NetworkManager/1.2/nm-dbus-types.html

**Comment by da2x** [comment]
…and it does. So I’m just wasting time.

**Comment by da2x** [comment]
No, it doesn’t. The [NMMetered](https://developer.gnome.org/NetworkManager/1.2/nm-dbus-types.html#NMMetered) constants are missing.

**Comment by seveas** [comment]
Added now, thanks!
