### ISSUE TITLE
Manual IPv4 setup does not work

### ISSUE THREAD

**Issue by phoracek** [seveas/python-networkmanager#40]
**Description of problem:**
When adding a new connection with manual IPv4 settings it fails because of invalid type. However, according to nm-settings documentation I'm using it right (correct me if I am wrong). "Array of IPv4 addresses. Each address dictionary contains at least 'address' and 'prefix' entries, containing the IP address as a string, and the prefix length as a uint32."

**Version-Release number of selected component (if applicable):**
python-networkmanager (2.0.1)
Python 3.4.5

**How reproducible:**
Always

**Steps to Reproduce:**
1. Create a connection with manual IP address settings:
```python
'ipv4': {
    'method': 'manual',
    'address-data': [{'address': '192.168.1.1', 'prefix': 24}]
}
```

**Actual results:**
Fails with "TypeError: Expected a string or unicode object"

**Expected results:**
Creates a connection with static IP.

**Reproduction:**
```python
[root@localhost ~]# python3
>>> import NetworkManager
>>> import uuid
>>> bridge_with_manual_ip = {
...     'connection': {
...         'id': 'br1',
...         'uuid': str(uuid.uuid4()),
...         'type': 'bridge',
...         'interface-name': 'br1'
...     },
...     'ipv4': {
...         'method': 'manual',
...         'address-data': [{'address': '192.168.1.1', 'prefix': 24}]
...     }
... }
>>> NetworkManager.Settings.AddConnection(bridge_with_manual_ip)
ERROR:dbus.connection:Unable to set arguments ({'ipv4': {'address-data': [{'address': '192.168.1.1', 'prefix': 24}], 'method': 'manual'}, 'connection': {'type': 'bridge', 'interface-name': 'br1', 'uuid': '240f360c-f005-4be1-b2ab-adfb596ac7e7', 'id': 'br1'}},) according to signature 'a{sa{sv}}': <class 'TypeError'>: Expected a string or unicode object
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 4, in AddConnection
  File "/usr/lib64/python3.4/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.4/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.4/site-packages/dbus/connection.py", line 641, in call_blocking
    message.append(signature=signature, *args)
TypeError: Expected a string or unicode object
```

**Comment by ctc** [comment]
Try this way:
`ip4 = {
                        'method':'manual',
                        'addresses': [[ config['ip4']['address'], net.prefixlen, config['ip4']['gateway']]],
                        'dns': []
                    }`

**Comment by phoracek** [comment]
Hey @ctc, thanks. This issue is so old. If I recall it correctly, the deprecated "addresses" method worked. However, I wanted to go with the new "address-data".

**Comment by isedev** [comment]
I think you can close this issue now.

**Comment by phoracek** [comment]
Yea, right :) Thanks guys.
