### ISSUE TITLE
AttributeError: type object 'Device' has no attribute 'all'

### ISSUE THREAD

**Issue by Thecave3** [seveas/python-networkmanager#45]
I called the file network.py instaed of wifi_monitor.py . Other examples like info.py works properly.

`Traceback (most recent call last):
  File "network.py", line 42, in <module>
    main()
  File "network.py", line 15, in main
    for dev in NetworkManager.Device.all():
AttributeError: type object 'Device' has no attribute 'all'
`

https://github.com/seveas/python-networkmanager/blob/aea55e82cfd888e12bb4cd7b7c4fffba1a6c09ba/examples/wifi_monitor.py#L15

I tried to run with python 2.7 and  python3 and had the same result. Still available for any info.

**Comment by seveas** [comment]
Then you're not using python-networkmanager :smile: The Device class most definitely has an all method.
