### ISSUE TITLE
AttributeError: 'AccessPoint' object has no attribute 'Ssid'

### ISSUE THREAD

**Issue by vidstige** [seveas/python-networkmanager#46]
Sometimes I get this error. Very unclear how this happens. At the same time `nmcli` can list networks fine... :thinking:

**Comment by seveas** [comment]
Do you have a traceback of this error?

**Comment by vidstige** [comment]
I tried to search our logs, but could not find this exception. I've since moved over to just invoking `nmcli` from command line as that was a bit more stable.
