### ISSUE TITLE
Invalid property: psk

### ISSUE THREAD

**Issue by kobylyanskiy** [seveas/python-networkmanager#47]
Hello everyone,
I'm trying to add connection to NetworkManager via python-networkmanager and got `dbus.exceptions.DBusException: org.freedesktop.NetworkManager.Settings.Connection.InvalidProperty: 802-11-wireless-security.psk: property is invalid`

In your examples, an open network is created, but I want to add secure network. My code looks like this:

    def add_network(self, ssid, password):

        connection = {
            '802-11-wireless': {
                'mode': 'infrastructure',
                'ssid': ssid
            },

            '802-11-wireless-security': {
                'key-mgmt': 'wpa-psk',
                'auth-alg': 'open',
                'psk': password,
            },

            'connection': {
                'id': ssid,
                'type': '802-11-wireless',
                'uuid': str(uuid.uuid4())
            },

            'ipv4': {'method': 'auto'},
            'ipv6': {'method': 'auto'}
        }

        NetworkManager.Settings.AddConnection(connection)

Is this a bug in python-networkmanager or I'm just doing something wrong? Thank you.

**Comment by rusty71** [comment]
For me this works:

    cube_conn = {u'802-11-wireless': {
                          u'mode': u'infrastructure',
                          u'security': u'802-11-wireless-security',
                          u'ssid': u'cube+me'},
     u'802-11-wireless-security': {u'auth-alg': u'open',
                                   u'group': [],
                                   u'key-mgmt': u'wpa-psk',
                                   u'pairwise': [],
                                   u'proto': [],
                                   u'psk': u'1234567890'},
     u'connection': {u'id': u'cube+me',
                     u'type': u'802-11-wireless',
                     u'uuid': str(uuid.uuid4())},
     u'ipv4': {u'method': u'auto'},
     u'ipv6': {u'method': u'auto'}
    }
