### ISSUE TITLE
Compatility with Ubuntu 14.04?

### ISSUE THREAD

**Issue by vanities** [seveas/python-networkmanager#56]
Hello! I'm using a legacy system with Ubuntu 14.04 with upstart as the init system and was wondering if we can get this package working with dbus 1.6.

When installing I get this error:
```
configure: error: Package requirements (dbus-1 >= 1.8) were not met:

Requested 'dbus-1 >= 1.8' but version of dbus is 1.6.18
```

**Comment by seveas** [comment]
that's not an error thrown by python-networkmanager. Can you share the command you're using to install, and the full output?

**Comment by vanities** [comment]
I'm sorry, I had to install dbus-python through https://github.com/posborne/dbus-python instructions rather than as a dependency from pip and got it working. Thanks for responding back. 

I have another question about deleting connections like `nmcli c delete id <id>` does in the command line. I've been searching around and can't seem to find a way of doing that, maybe I'm missing it? 
`NetworkManager.Settings.DeleteConnection(connection)` maybe?
