### ISSUE TITLE
React to activating/deactivating a connection

### ISSUE THREAD

**Issue by Voidi** [seveas/python-networkmanager#61]
I want to execute my code after a connection is enabled and before it gets disabled. (Similar to the NetworkManager-Dispatcher events `up` and `pre-down`.
In addition i want the Connection object of the changing connection. (i need to compare the uuids).
How can i accomplish this?
`NetworkManager.NetworkManager.OnStateChanged` does not contain information which connection changed.
Furthermore how could i do something like `pre-down`, as the NetworkManager API doesn't seem to have a signal/event like this?

**Comment by Mryashbhardwaj** [comment]
Can i  take this up ?

**Comment by seveas** [comment]
Closing all PR's and issues prior to archiving this repository.
