### ISSUE TITLE
Wrong enum mapping for connectivity state flags

### ISSUE THREAD

**Issue by dulwin** [seveas/python-networkmanager#63]
The NM_CONNECTIVITY_* flags are mapped incorrectly.
The correct definition is: 
https://people.freedesktop.org/~lkundrak/nm-docs/nm-dbus-types.html#NMConnectivityState

however the values defined in the api are 0 indexed:
https://github.com/seveas/python-networkmanager/blob/master/NetworkManager.py#L751-L755

**Comment by sunbearc22** [comment]
Is there typos caused by `makeconstants.py`?

**Comment by dulwin** [comment]
Sorry after looking into https://github.com/NetworkManager/NetworkManager/blob/cee8b56d3fdc0b866a55125d52bc0d845c997fdb/libnm-util/NetworkManager.h#L122-L128 and https://developer.gnome.org/NetworkManager/stable/nm-dbus-types.html it appears the documentation I was using were outdated/incorrect. Thanks for taking the time!
