### ISSUE TITLE
Question about Device.Reapply()

### ISSUE THREAD

**Issue by ymolinet** [seveas/python-networkmanager#78]
Hi,

I'm need to invoke Device.Reapply()
From documentation (https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Device.html), an if I understand, this method take 3 args that can be null or empty.

If I invoke device.Reapply() in my python script, I received an error

TypeError: Reapply() takes exactly 4 arguments

Could you explain how to use it correctly ?

Thanks,
Yannick

**Comment by Hadatko** [comment]
Hi, if i am not wrong then when you call reapply on device instance it takes 3 args. If you call general Device.Reapply() function it takes 4 args because one is device instance.

**Comment by seveas** [comment]
Closing all PR's and issues prior to archiving this repository.
