### ISSUE TITLE
AttributeError: "NetworkManager" object has no attribute 'OnPropertiesChanged'

### ISSUE THREAD

**Issue by Zocker1999NET** [seveas/python-networkmanager#89]
I used to access the signal `OnPropertiesChanged` by calling `NetworkManager.NetworkManager.OnPropertiesChanged()`, however this stopped working, probably after upgrading the package network-manager:amd64 on my Debian system from 1.30.6-1 to 1.32.12-1. I get the following traceback:

```
Traceback (most recent call last):
  File "/home/zocker/.config/sway/python/status.py", line 1445, in <module>
    NetworkStatus(
  File "/home/zocker/.config/sway/python/status.py", line 1042, in __init__
    NetworkManager.NetworkManager.OnPropertiesChanged(self.__handler)
AttributeError: 'NetworkManager' object has no attribute 'OnPropertiesChanged'
```

Any ideas on how to access this signal?

**Comment by ojob** [comment]
Same issue, with Ubuntu 21.10.

So I forked this project some hours ago, and tried to follow the link above in order to propose a pull request, to no avail: while willing to help, the package structure is just too opaque for me.

Any hint to get me started?

**Comment by seveas** [comment]
Closing all PR's and issues prior to archiving this repository.
